{
 "title": "Internet connection",
 "tags": [ "http" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "HTTP Uptime",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"http\"}",
     "legendFormat": "{{humanname}}"
    }
   ]
  },
  {
   "title": "ICMP Uptime",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_success{job=\"icmp\"}",
     "legendFormat": "{{humanname}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{humanname}}"
    }
   ]
  }
 ]
}